%
%simon <nicksimon@gmail.com>
%2015-05-19 16:06
%

%according sample of alice and bob to generate keys
function ret=generate_key(a,b)
    qa=threshold(a);
    list=seq(a,qa);
    %if seq empty,then flag ret and return
    if(list(1)==0)
        ret=-1;
        return
    end
    qb=threshold(b);
    key_list=seq_final(b,list,qb);
    if(key_list(1)==0)
        ret=-1;
        return
    end
    %print key generated by alice
    for i=1:size(key_list,2)
        pos=key_list(i);
        rss=a(pos);
        flag=quant(rss,qa);
        if(flag==1)
            ret(1,i)=1;
        else
            ret(1,i)=0;
        end
    end
    %print key generated by bob
    for i=1:size(key_list,2)
        pos=key_list(i);
        rss=b(pos);
        flag=quant(rss,qb);
        if(flag==1)
            ret(2,i)=1;
        else
            ret(2,i)=0;
        end
    end
end